"""Initial migration.

Revision ID: 462ee37e6dad
Revises: 
Create Date: 2023-03-09 21:53:21.645183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462ee37e6dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_model_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_model_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_model_title'))
        batch_op.drop_index(batch_op.f('ix_books_model_description'))

    op.drop_table('books_model')
    # ### end Alembic commands ###
